# CONFIGURAÇÃO PARA MYSQL (não MariaDB!)
spring.datasource.url=jdbc:mysql://localhost:3306/bloodApp
spring.datasource.username=root
spring.datasource.password=

# Configurações do JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.address=0.0.0.0
